---
deployment:
  tasks:
    - export DEPLOYPATHP=/home/artphoto/test.art-photo.mk/
    - export DEPLOYPATH=/home/artphoto/testapp/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R public/* $DEPLOYPATHP